version: '2'
services:
  mongodb:
    image: mongo:3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: graylog/graylog:3.0
    environment:
      - GRAYLOG_PASSWORD_SECRET=demeksimdigidiyorsun.*
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=b718f1354f7247312eca086d9a024afe5fa717ddea5adeddd6f12bcf945b2e8c
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:3000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 3000:9000 # Graylog web interface and REST API
      - 3001:5555 # Raw/Plaintext TCP
      - 3002:1514 # Syslog TCP
      - 3002:1514/udp # Syslog UDP
      - 3003:12201 # GELF TCP
      - 3003:12201/udp # GELF UDP